
package vista;
//import controlador.Reportes;
import javax.swing.JDesktopPane;
import java.awt.Dimension;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Angel
 */
public class FrmAdministrador extends javax.swing.JFrame {
public static JDesktopPane jDesktopPane_menu;

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Concesionario");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        miBotonColores1 = new componente.MiBotonColores();
        jMenuBar1 = new javax.swing.JMenuBar();
        empleados = new javax.swing.JMenu();
        nuevoEmpleado = new javax.swing.JMenuItem();
        gestionarEmpleado = new javax.swing.JMenuItem();
        inventarios = new javax.swing.JMenu();
        agregarInventario = new javax.swing.JMenuItem();
        gestionarInventario = new javax.swing.JMenuItem();
        jMenuItem_actualizar_stock = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenu();
        agregarCliente = new javax.swing.JMenuItem();
        gestionarCliente = new javax.swing.JMenuItem();
        ventas = new javax.swing.JMenu();
        gestionVentas = new javax.swing.JMenuItem();
        clientes1 = new javax.swing.JMenu();
        gestionarCliente1 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRADOR");

        btnSalir.setBackground(new java.awt.Color(51, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Cerrar Secion");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        miBotonColores1.setText("Cambiar Diseño");

        empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        empleados.setText("Empleados");
        empleados.setPreferredSize(new java.awt.Dimension(150, 50));

        nuevoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        nuevoEmpleado.setText("Nuevo Empleado");
        nuevoEmpleado.setPreferredSize(new java.awt.Dimension(200, 50));
        nuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(nuevoEmpleado);

        gestionarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        gestionarEmpleado.setText("Gestionar Empleados");
        gestionarEmpleado.setPreferredSize(new java.awt.Dimension(200, 50));
        gestionarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarEmpleadoActionPerformed(evt);
            }
        });
        empleados.add(gestionarEmpleado);

        jMenuBar1.add(empleados);

        inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        inventarios.setText("Inventario");
        inventarios.setPreferredSize(new java.awt.Dimension(200, 50));

        agregarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        agregarInventario.setText("Agregar Inventario");
        agregarInventario.setPreferredSize(new java.awt.Dimension(200, 50));
        agregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInventarioActionPerformed(evt);
            }
        });
        inventarios.add(agregarInventario);

        gestionarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        gestionarInventario.setText("Gestinar Inventario");
        gestionarInventario.setPreferredSize(new java.awt.Dimension(200, 50));
        gestionarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarInventarioActionPerformed(evt);
            }
        });
        inventarios.add(gestionarInventario);

        jMenuItem_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem_actualizar_stock.setText("Actualizar Cantidad");
        jMenuItem_actualizar_stock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_actualizar_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_actualizar_stockActionPerformed(evt);
            }
        });
        inventarios.add(jMenuItem_actualizar_stock);

        jMenuBar1.add(inventarios);

        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        clientes.setText("Clientes");
        clientes.setPreferredSize(new java.awt.Dimension(200, 50));

        agregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        agregarCliente.setText("Agregar Cliente");
        agregarCliente.setPreferredSize(new java.awt.Dimension(200, 50));
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        clientes.add(agregarCliente);

        gestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        gestionarCliente.setText("Gestionar Clientes");
        gestionarCliente.setPreferredSize(new java.awt.Dimension(200, 50));
        gestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarClienteActionPerformed(evt);
            }
        });
        clientes.add(gestionarCliente);

        jMenuBar1.add(clientes);

        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        ventas.setText("Ventas");

        gestionVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        gestionVentas.setText("Gestionar Ventas");
        gestionVentas.setPreferredSize(new java.awt.Dimension(200, 50));
        gestionVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionVentasActionPerformed(evt);
            }
        });
        ventas.add(gestionVentas);

        jMenuBar1.add(ventas);

        clientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        clientes1.setText("Categoria");
        clientes1.setPreferredSize(new java.awt.Dimension(200, 50));

        gestionarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        gestionarCliente1.setText("Gestionar Categoria");
        gestionarCliente1.setPreferredSize(new java.awt.Dimension(200, 50));
        gestionarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarCliente1ActionPerformed(evt);
            }
        });
        clientes1.add(gestionarCliente1);

        jMenuBar1.add(clientes1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1206, 1206, 1206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(miBotonColores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir))
                    .addComponent(jLabel1))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(miBotonColores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarClienteActionPerformed
      AdministrarCliente interGestionarCliente = new AdministrarCliente();
        jDesktopPane_menu.add(interGestionarCliente);
        interGestionarCliente.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_gestionarClienteActionPerformed

    private void nuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEmpleadoActionPerformed
 AgregarEmpleado interEmpleado = new AgregarEmpleado();
        jDesktopPane_menu.add(interEmpleado);
        interEmpleado.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoEmpleadoActionPerformed

    private void gestionarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarEmpleadoActionPerformed
 AdministrarEmpleado interGestionarEmpleado = new AdministrarEmpleado();
        jDesktopPane_menu.add(interGestionarEmpleado);
        interGestionarEmpleado.setVisible(true);
               // jDesktopPane_menu.add(interGestionarEmpleado);
                
      // TODO add your handling code here:
    }//GEN-LAST:event_gestionarEmpleadoActionPerformed

    private void agregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInventarioActionPerformed
    AgregarMoto interInventario = new AgregarMoto();
        jDesktopPane_menu.add(interInventario);
        interInventario.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_agregarInventarioActionPerformed

    private void gestionarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarInventarioActionPerformed
AdministrarInventarioAdministrador interGestionarInventario = new AdministrarInventarioAdministrador();
        jDesktopPane_menu.add(interGestionarInventario);
        interGestionarInventario.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarInventarioActionPerformed

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
AgregarCliente interCliente = new AgregarCliente();
        jDesktopPane_menu.add(interCliente);
        interCliente.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
  Login login = new Login();
        login.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void gestionVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionVentasActionPerformed
     AdministarVentas interGestionarVentas = new AdministarVentas();
        jDesktopPane_menu.add(interGestionarVentas);
        interGestionarVentas.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_gestionVentasActionPerformed

    private void gestionarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarCliente1ActionPerformed
GestionarCategoria gestionarcat = new   GestionarCategoria();
 jDesktopPane_menu.add(gestionarcat);
        gestionarcat.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_gestionarCliente1ActionPerformed

    private void jMenuItem_actualizar_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_actualizar_stockActionPerformed
        ActualizarStock interActualizarStock = new ActualizarStock();
        jDesktopPane_menu.add(interActualizarStock);
        interActualizarStock.setVisible(true);
    }//GEN-LAST:event_jMenuItem_actualizar_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarCliente;
    private javax.swing.JMenuItem agregarInventario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu clientes;
    private javax.swing.JMenu clientes1;
    private javax.swing.JMenu empleados;
    private javax.swing.JMenuItem gestionVentas;
    private javax.swing.JMenuItem gestionarCliente;
    private javax.swing.JMenuItem gestionarCliente1;
    private javax.swing.JMenuItem gestionarEmpleado;
    private javax.swing.JMenuItem gestionarInventario;
    private javax.swing.JMenu inventarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem_actualizar_stock;
    private componente.MiBotonColores miBotonColores1;
    private javax.swing.JMenuItem nuevoEmpleado;
    private javax.swing.JMenu ventas;
    // End of variables declaration//GEN-END:variables
}
